import { useEffect, useRef, useState } from 'react'
import { getDashboardInsights } from '../api'

const REFRESH_MS = 20000

function toBullets(text) {
  return text
    .split('\n')
    .map((line) => line.replace(/^[\s*•\-]+/, '').trim())
    .filter(Boolean)
}

export default function InsightsPanel() {
  const [data, setData] = useState(null)
  const [error, setError] = useState(null)
  const pollRef = useRef(null)

  useEffect(() => {
    let cancelled = false

    async function poll() {
      try {
        const result = await getDashboardInsights()
        if (!cancelled) {
          setData(result)
          setError(null)
        }
      } catch (e) {
        if (!cancelled) setError(e.message)
      }
    }

    poll()
    pollRef.current = setInterval(poll, REFRESH_MS)
    return () => {
      cancelled = true
      clearInterval(pollRef.current)
    }
  }, [])

  return (
    <div className="panel insights-panel">
      <p className="panel-title">Actionable Insights</p>

      {error && <div className="error-message">Failed to load insights: {error}</div>}

      {!error && data?.error && (
        <div className="insights-empty">{data.error}</div>
      )}

      {!error && !data?.error && !data?.insights && (
        <div className="loading">Generating insights…</div>
      )}

      {!error && data?.insights && (
        <>
          <ul className="insights-list">
            {toBullets(data.insights).map((line, i) => (
              <li key={i}>{line}</li>
            ))}
          </ul>
          <p className="insights-meta">
            Generated by {data.model} · {new Date(data.generated_at).toLocaleTimeString()}
          </p>
        </>
      )}
    </div>
  )
}
